import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Sparkles, Lightbulb, Shield, TrendingUp, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useWeatherAI } from '@/hooks/useWeatherAI';
import { useToast } from '@/components/ui/use-toast';

interface WeatherInsightsProps {
  weatherData: any;
  location: string;
  className?: string;
}

const WeatherInsights = ({ weatherData, location, className = "" }: WeatherInsightsProps) => {
  const { insights, loading, error, getWeatherInsights } = useWeatherAI();
  const { toast } = useToast();
  const [autoGenerated, setAutoGenerated] = useState(false);

  useEffect(() => {
    if (weatherData && !autoGenerated) {
      handleGenerateInsights();
      setAutoGenerated(true);
    }
  }, [weatherData]);

  useEffect(() => {
    if (error) {
      toast({
        title: "AI Insights Error",
        description: error,
        variant: "destructive",
      });
    }
  }, [error, toast]);

  const handleGenerateInsights = async () => {
    await getWeatherInsights(weatherData, location, 'insights');
  };

  if (!insights && !loading) {
    return (
      <div className={`weather-card text-center ${className}`}>
        <div className="mb-4">
          <Sparkles className="w-12 h-12 text-neon-primary mx-auto mb-3" />
          <h3 className="text-lg font-semibold text-foreground mb-2">AI Weather Insights</h3>
          <p className="text-sm text-muted-foreground mb-4">
            Get intelligent weather analysis and personalized recommendations
          </p>
        </div>
        <Button 
          onClick={handleGenerateInsights}
          className="bg-gradient-primary text-white neon-glow"
          disabled={loading}
        >
          <Sparkles className="w-4 h-4 mr-2" />
          Generate Insights
        </Button>
      </div>
    );
  }

  return (
    <motion.div
      className={`weather-card ${className}`}
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center space-x-2">
          <Sparkles className="w-6 h-6 text-neon-primary" />
          <h2 className="text-xl font-semibold text-foreground">AI Insights</h2>
        </div>
        <Button
          variant="ghost"
          size="sm"
          onClick={handleGenerateInsights}
          disabled={loading}
          className="text-neon-primary hover:bg-neon-primary/10"
        >
          <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
        </Button>
      </div>

      {loading ? (
        <div className="space-y-4 animate-pulse">
          <div className="h-4 bg-glass rounded w-3/4"></div>
          <div className="h-4 bg-glass rounded w-1/2"></div>
          <div className="space-y-2">
            <div className="h-3 bg-glass rounded w-full"></div>
            <div className="h-3 bg-glass rounded w-5/6"></div>
          </div>
        </div>
      ) : insights ? (
        <div className="space-y-6">
          {/* Summary */}
          {insights.summary && (
            <motion.div
              className="p-4 glass rounded-lg"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.1 }}
            >
              <div className="flex items-start space-x-3">
                <TrendingUp className="w-5 h-5 text-neon-primary mt-1" />
                <div>
                  <h3 className="font-medium text-foreground mb-1">Weather Summary</h3>
                  <p className="text-sm text-muted-foreground">{insights.summary}</p>
                </div>
              </div>
            </motion.div>
          )}

          {/* Recommendations */}
          {insights.recommendations && (
            <motion.div
              className="p-4 glass rounded-lg"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.2 }}
            >
              <div className="flex items-start space-x-3">
                <Lightbulb className="w-5 h-5 text-neon-warning mt-1" />
                <div className="flex-1">
                  <h3 className="font-medium text-foreground mb-2">Recommendations</h3>
                  <div className="space-y-1">
                    {Array.isArray(insights.recommendations) ? (
                      insights.recommendations.map((rec, index) => (
                        <div key={index} className="text-sm text-muted-foreground flex items-start">
                          <span className="text-neon-primary mr-2">•</span>
                          {rec}
                        </div>
                      ))
                    ) : (
                      <p className="text-sm text-muted-foreground">{insights.recommendations}</p>
                    )}
                  </div>
                </div>
              </div>
            </motion.div>
          )}

          {/* Insight */}
          {insights.insight && (
            <motion.div
              className="p-4 glass rounded-lg"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.3 }}
            >
              <div className="flex items-start space-x-3">
                <Sparkles className="w-5 h-5 text-neon-secondary mt-1" />
                <div>
                  <h3 className="font-medium text-foreground mb-1">Weather Science</h3>
                  <p className="text-sm text-muted-foreground">{insights.insight}</p>
                </div>
              </div>
            </motion.div>
          )}

          {/* Safety */}
          {insights.safety && (
            <motion.div
              className="p-4 glass rounded-lg border border-neon-warning/30"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.4 }}
            >
              <div className="flex items-start space-x-3">
                <Shield className="w-5 h-5 text-neon-warning mt-1" />
                <div>
                  <h3 className="font-medium text-foreground mb-1">Safety Note</h3>
                  <p className="text-sm text-muted-foreground">{insights.safety}</p>
                </div>
              </div>
            </motion.div>
          )}
        </div>
      ) : (
        <div className="text-center text-muted-foreground">
          <p>Unable to generate insights. Please try again.</p>
        </div>
      )}
    </motion.div>
  );
};

export default WeatherInsights;