// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrkqlriphaprufnkyfho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhya3FscmlwaGFwcnVmbmt5ZmhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTM4NzIsImV4cCI6MjA3MTM2OTg3Mn0.79Fk3ieJo6VCLZQlqa-2WFNfcm4o_Ae3lPpKQq2t7aU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});